version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: yourdb
      DB_USER: youruser
      DB_PASSWORD: yourpassword
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: 